- hosts: all
  become: yes
  tasks:
    - group:
        name: dev
        state: present
    - name: Set /var/www permissions
      file:
        path: /var/www/
        # owner: dev  
        group: dev
        state: directory
        recurse: yes
        mode: 0775
    - include_role:
        name: users


